sonar.projectKey=MatheussBrant_gces-projeto-individual
sonar.organization=matheussbrant
sonar.host.url=https://sonarcloud.io

sonar.projectName=gces-projeto-individual
sonar.sourceEncoding=UTF-8

sonar.sources=server,game/src
sonar.tests=test
sonar.exclusions=server/node_modules/**,node_modules/**,coverage/**
sonar.test.inclusions=test/**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.qualitygate.wait=true

