apiVersion: v1
kind: Secret
metadata:
  name: mkjs-secrets
  namespace: gces-projeto-individual
type: Opaque
stringData:
  POSTGRES_DB: mkjs
  POSTGRES_USER: mkjs
  POSTGRES_PASSWORD: mkjs
  DATABASE_URL: postgres://mkjs:mkjs@postgres:5432/mkjs

